### ISSUE TITLE
Implement signature verification

### ISSUE THREAD

**Issue by gr2m** [gr2m/cloudflare-worker-github-app-example#1]
The requests from GitHub are currently not verified using the signature, because [the code is currently using Node's crypto package](https://github.com/octokit/webhooks.js/blob/0e03e470034ac769a28ed37acb524b94e304bf96/src/sign/index.ts#L1). This will be resolved once I create a universal webhook verification package, similar to [`universal-github-app-jwt`](https://github.com/gr2m/universal-github-app-jwt/#readme). For the time being, you could define a secret path that that webhook requests by GitHub are sent to, in order to prevent anyone who knows your workers URL from sending fake webhook requests.

**Comment by boredland** [comment]
Does this mean that the disclaimer in the README is kinda outdated?
